networks:
  bridge:

services:
  postgres:
    image: postgres:16-alpine3.19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/postgresql/data"
    networks:
      - bridge
  media-server:
    build:
      target: media-server-bin
    command:
      - /app/media-server
    ports:
      - 8080:8080
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
    # environment:
    # Must be addr of your VPS
    #     WEBRTC_ONE_TO_NAT_PUBLIC_IP: 0.0.0.0
    networks:
      - bridge
    develop:
      watch:
        - action: rebuild
          path: media-server
          target: /app/media-server
        - action: rebuild
          path: pkg
          target: /app/pkg
  # gateway:
  #   build:
  #     target: gateway
  #     args:
  #       DOMAIN: localhost
  #       VITE_MEDIA_SERVER: https://localhost/api
  #       VITE_MEDIA_SERVER_WS: wss://localhost/api
  #       # VITE_MEDIA_SERVER_STUN: stun:stun.l.google.com:19302
  #   environment:
  #     CERT_DIR_RESET: false
  #     BASE64_FULL_CHAIN:
  #     BASE64_PRIV_KEY:
  #   ports:
  #     - 443:443
  #     - 80:80
  #   networks:
  #     - bridge
  #   volumes:
  #       - /etc/letsencrypt
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: certs.sh
  #         target: /app/certs.sh
  #       - action: sync+restart
  #         path: nginx.templ.conf
  #         target: /app/nginx.templ.conf
