networks:
  bridge:

services:
  media-server:
    build:
      target: media-server-bin
    command:
      - /app/media-server
    networks:
      - bridge
    develop:
      watch:
        - action: rebuild
          path: media-server
          target: /app/media-server
        - action: rebuild
          path: pkg
          target: /app/pkg
  gateway:
    build:
      target: gateway
      args:
        DOMAIN: localhost
        VITE_MEDIA_SERVER: http://localhost/api
        VITE_MEDIA_SERVER_WS: wss://localhost/api
    ports:
      - 443:443
    networks:
      - bridge
    volumes:
        - /etc/letsencrypt
    develop:
      watch:
        - action: sync+restart
          path: certs.sh
          target: /app/certs.sh
        - action: sync+restart
          path: nginx.templ.conf
          target: /app/nginx.templ.conf
