// Package room provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package room

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Participant defines model for Participant.
type Participant struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Room defines model for Room.
type Room struct {
	Host         *string        `json:"host,omitempty"`
	Participants *[]Participant `json:"participants,omitempty"`
	Port         *string        `json:"port,omitempty"`
	SessionID    *string        `json:"sessionID,omitempty"`
}

// RoomCreateRequest defines model for RoomCreateRequest.
type RoomCreateRequest struct {
	MaxParticipants *int32 `json:"maxParticipants,omitempty"`
}

// RoomCreateResponse defines model for RoomCreateResponse.
type RoomCreateResponse struct {
	Room *Room `json:"room,omitempty"`
}

// RoomDeleteResponse defines model for RoomDeleteResponse.
type RoomDeleteResponse = map[string]interface{}

// RoomListResponse defines model for RoomListResponse.
type RoomListResponse struct {
	Rooms *[]Room `json:"rooms,omitempty"`
}

// RoomControllerRoomCreateJSONRequestBody defines body for RoomControllerRoomCreate for application/json ContentType.
type RoomControllerRoomCreateJSONRequestBody = RoomCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /rooms)
	RoomControllerRoomList(ctx echo.Context) error

	// (POST /rooms)
	RoomControllerRoomCreate(ctx echo.Context) error

	// (DELETE /rooms/{sessionID})
	RoomControllerRoomDelete(ctx echo.Context, sessionID string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RoomControllerRoomList converts echo context to params.
func (w *ServerInterfaceWrapper) RoomControllerRoomList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RoomControllerRoomList(ctx)
	return err
}

// RoomControllerRoomCreate converts echo context to params.
func (w *ServerInterfaceWrapper) RoomControllerRoomCreate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RoomControllerRoomCreate(ctx)
	return err
}

// RoomControllerRoomDelete converts echo context to params.
func (w *ServerInterfaceWrapper) RoomControllerRoomDelete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionID" -------------
	var sessionID string

	err = runtime.BindStyledParameterWithLocation("simple", false, "sessionID", runtime.ParamLocationPath, ctx.Param("sessionID"), &sessionID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RoomControllerRoomDelete(ctx, sessionID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/rooms", wrapper.RoomControllerRoomList)
	router.POST(baseURL+"/rooms", wrapper.RoomControllerRoomCreate)
	router.DELETE(baseURL+"/rooms/:sessionID", wrapper.RoomControllerRoomDelete)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUzW7bTAx8lQ/8ehQsNb7pljSXoAVqpEdDh41EWxtIu1suXdQw9O4FKcs/suK6RXOx",
	"JXGXnBkOuYPSt8E7dBwh30Esa2yNPi4MsS1tMI7lNZAPSGxRg7aSX94GhBwik3Vr6BJwpsWJQJcMX/zL",
	"K5YsR5+9by/z1j7yZOZwRNMDYGz14QPhCnL4Pz0SSfcs0lMKRwyGyGw1p6fpYhFjtN49Pf4Bl0+EhvEZ",
	"v28wTgjWmp+LEYWVp9Yw5GAdz+/gkNc6xjXS70vF4F3Ey1q0l/aaNCr/mxUescHzCpPHvtjI12Hc3qse",
	"0LhJlwC1PeWGLG+/ydW+1gMaQrrfcH1wsVx60c9HaWvmAJ3ksG7llZflRiKqq3dMvmmQ/rtfPEECP5DE",
	"B5BDNstmHwWeD+hMsJDDfJbN5iDO5FoxpAfCa1QHiBiGxUjVRYVBPkiA9grq1bssk7/SO8Z+8EwIjS01",
	"T/oaBc0wprdIetYiZV5hLMkG7ol9/dyLbNYR8uUIJBQ6JfEmNr0rlY/OwIOvtv+UyvmEKRcpZQkryJk2",
	"2L2zlqO5e1vNwaCQL8+tuSy64orYXbI3Ubo7rKBOkFU6j7d0oZ9ctSWZFhkpKgor8MSqMGzpky03FjI5",
	"EWW8/op3Fnm0ev7CsifB3cB1dKgrul8BAAD//xZX+PT6BgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
